version: "3.7"

services:
  scraper:
    image: ghcr.io/tomwphillips/agile-rates:main
    command: --database-url "sqlite:///data/agile.db" daemon
    volumes:
      - agile_scraper_data:/home/scraper/src/data/
  datasette:
    image: datasetteproject/datasette:0.64.3
    command: datasette -p 8001 -h 0.0.0.0 /data/agile.db
    volumes:
      - agile_scraper_data:/data:ro
  caddy:
    image: caddy:2.6.4-alpine
    command: caddy reverse-proxy --from agile.tomwphillips.co.uk --to datasette:8001
    ports:
      - 443:443

volumes:
  agile_scraper_data:
