"""Create tables

Revision ID: d978d21b819c
Revises:
Create Date: 2023-04-27 19:40:39.693421

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d978d21b819c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("code", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "tariffs",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("product_code", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_code"],
            ["products.code"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "unit_rates",
        sa.Column("tariff_code", sa.String(), nullable=True),
        sa.Column("valid_from", sa.DateTime(), nullable=True),
        sa.Column("valid_to", sa.DateTime(), nullable=True),
        sa.Column("value_exc_vat", sa.Float(), nullable=True),
        sa.Column("value_inc_vat", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tariff_code"],
            ["tariffs.code"],
        ),
        sa.UniqueConstraint("tariff_code", "valid_from", "valid_to"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unit_rates")
    op.drop_table("tariffs")
    op.drop_table("products")
    # ### end Alembic commands ###
