name: Packages
on:
  push:
    branches:
      - main

jobs:
  delete-agile-rates:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: agile-rates
          package-type: container
          min-versions-to-keep: 0
