name: Scraper
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2.5.0

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build Docker test image
        uses: docker/build-push-action@v4.0.0
        with:
          context: "{{defaultContext}}:scraper" # switch to scraper/ subdir
          target: tests
          load: true
          tags: tests

      - name: Run tests
        run: docker run --rm tests

      - name: Build and push Docker app image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4.0.0
        with:
          context: "{{defaultContext}}:scraper" # switch to scraper/ subdir
          target: app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
